driver: pgsql
host: ${PGHOST}
port: ${PGPORT}
database: ${PGDATABASE}
username: ${PGUSER}
password: ${PGPASSWORD}
options:
  ATTR_ERRMODE: ERRMODE_EXCEPTION
  ATTR_DEFAULT_FETCH_MODE: FETCH_ASSOC
  ATTR_EMULATE_PREPARES: false